# Generated by Django 5.0.10 on 2025-01-09 16:44
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
    